[Tue Aug 22 12:12:17.247110 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112] mod_wsgi (pid=1162): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:12:17.247424 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112] mod_wsgi (pid=1162): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:12:17.247567 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112] Traceback (most recent call last):
[Tue Aug 22 12:12:17.247665 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:12:17.247958 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:12:17.248203 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:12:17.248240 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112]     raise AssertionError(msg) from exc
[Tue Aug 22 12:12:17.248265 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112]                                  ^
[Tue Aug 22 12:12:17.248288 2023] [wsgi:error] [pid 1162:tid 1974465536] [client 127.0.0.1:56112] SyntaxError: invalid syntax
[Tue Aug 22 12:12:17.660689 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114] mod_wsgi (pid=1162): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'., referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.660820 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114] mod_wsgi (pid=1162): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'., referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.660936 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114] Traceback (most recent call last):, referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661049 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>, referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661162 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec')), referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661338 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18, referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661366 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114]     raise AssertionError(msg) from exc, referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661391 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114]                                  ^, referer: http://127.0.0.1/
[Tue Aug 22 12:12:17.661414 2023] [wsgi:error] [pid 1162:tid 1963975680] [client 127.0.0.1:56114] SyntaxError: invalid syntax, referer: http://127.0.0.1/
[Tue Aug 22 12:13:43.749438 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116] mod_wsgi (pid=1161): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:43.749705 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116] mod_wsgi (pid=1161): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:43.749837 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116] Traceback (most recent call last):
[Tue Aug 22 12:13:43.749965 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:13:43.750373 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:13:43.750697 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:13:43.750814 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116]     raise AssertionError(msg) from exc
[Tue Aug 22 12:13:43.750842 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116]                                  ^
[Tue Aug 22 12:13:43.750865 2023] [wsgi:error] [pid 1161:tid 1974465536] [client 127.0.0.1:56116] SyntaxError: invalid syntax
[Tue Aug 22 12:13:45.339038 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118] mod_wsgi (pid=1162): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:45.339187 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118] mod_wsgi (pid=1162): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:45.339292 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118] Traceback (most recent call last):
[Tue Aug 22 12:13:45.339395 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:13:45.339515 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:13:45.339693 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:13:45.339721 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118]     raise AssertionError(msg) from exc
[Tue Aug 22 12:13:45.339745 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118]                                  ^
[Tue Aug 22 12:13:45.339770 2023] [wsgi:error] [pid 1162:tid 1934603264] [client 127.0.0.1:56118] SyntaxError: invalid syntax
[Tue Aug 22 12:13:46.359034 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120] mod_wsgi (pid=1162): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:46.359371 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120] mod_wsgi (pid=1162): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:13:46.359614 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120] Traceback (most recent call last):
[Tue Aug 22 12:13:46.359810 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:13:46.360055 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:13:46.360422 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:13:46.360550 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120]     raise AssertionError(msg) from exc
[Tue Aug 22 12:13:46.360578 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120]                                  ^
[Tue Aug 22 12:13:46.360605 2023] [wsgi:error] [pid 1162:tid 1913648128] [client 127.0.0.1:56120] SyntaxError: invalid syntax
[Tue Aug 22 12:16:24.579559 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130] mod_wsgi (pid=1161): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:16:24.579733 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130] mod_wsgi (pid=1161): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:16:24.579840 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130] Traceback (most recent call last):
[Tue Aug 22 12:16:24.579962 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:16:24.580109 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:16:24.580320 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:16:24.580407 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130]     raise AssertionError(msg) from exc
[Tue Aug 22 12:16:24.580434 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130]                                  ^
[Tue Aug 22 12:16:24.580457 2023] [wsgi:error] [pid 1161:tid 1955591168] [client 127.0.0.1:56130] SyntaxError: invalid syntax
[Tue Aug 22 12:16:25.995947 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132] mod_wsgi (pid=1161): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:16:25.996112 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132] mod_wsgi (pid=1161): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:16:25.996235 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132] Traceback (most recent call last):
[Tue Aug 22 12:16:25.996358 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:16:25.996500 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:16:25.996685 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:16:25.996715 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132]     raise AssertionError(msg) from exc
[Tue Aug 22 12:16:25.996740 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132]                                  ^
[Tue Aug 22 12:16:25.996763 2023] [wsgi:error] [pid 1161:tid 1926231040] [client 127.0.0.1:56132] SyntaxError: invalid syntax
[Tue Aug 22 12:18:16.913687 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136] mod_wsgi (pid=1161): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:18:16.913900 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136] mod_wsgi (pid=1161): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:18:16.914048 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136] Traceback (most recent call last):
[Tue Aug 22 12:18:16.914196 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:18:16.914399 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:18:16.914661 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:18:16.914708 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136]     raise AssertionError(msg) from exc
[Tue Aug 22 12:18:16.914737 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136]                                  ^
[Tue Aug 22 12:18:16.914764 2023] [wsgi:error] [pid 1161:tid 1896866816] [client 127.0.0.1:56136] SyntaxError: invalid syntax
[Tue Aug 22 12:18:18.636404 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138] mod_wsgi (pid=1161): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:18:18.636587 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138] mod_wsgi (pid=1161): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:18:18.636741 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138] Traceback (most recent call last):
[Tue Aug 22 12:18:18.636875 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:18:18.637032 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:18:18.637337 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:18:18.637392 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138]     raise AssertionError(msg) from exc
[Tue Aug 22 12:18:18.637422 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138]                                  ^
[Tue Aug 22 12:18:18.637449 2023] [wsgi:error] [pid 1161:tid 1888474112] [client 127.0.0.1:56138] SyntaxError: invalid syntax
[Tue Aug 22 12:19:22.738730 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140] mod_wsgi (pid=1720): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:19:22.739089 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140] mod_wsgi (pid=1720): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:19:22.739222 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140] Traceback (most recent call last):
[Tue Aug 22 12:19:22.739325 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:19:22.739603 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:19:22.739866 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:19:22.739914 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140]     raise AssertionError(msg) from exc
[Tue Aug 22 12:19:22.739944 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140]                                  ^
[Tue Aug 22 12:19:22.739971 2023] [wsgi:error] [pid 1720:tid 1973416960] [client 127.0.0.1:56140] SyntaxError: invalid syntax
[Tue Aug 22 12:20:29.687271 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142] mod_wsgi (pid=1808): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:29.710241 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142] mod_wsgi (pid=1808): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:29.710444 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142] Traceback (most recent call last):
[Tue Aug 22 12:20:29.710551 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:20:29.710886 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:20:29.711134 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:20:29.711175 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142]     raise AssertionError(msg) from exc
[Tue Aug 22 12:20:29.711202 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142]                                  ^
[Tue Aug 22 12:20:29.711225 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56142] SyntaxError: invalid syntax
[Tue Aug 22 12:20:32.306609 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144] mod_wsgi (pid=1808): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:32.306963 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144] mod_wsgi (pid=1808): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:32.307071 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144] Traceback (most recent call last):
[Tue Aug 22 12:20:32.307153 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:20:32.307311 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:20:32.307489 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:20:32.307515 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144]     raise AssertionError(msg) from exc
[Tue Aug 22 12:20:32.307540 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144]                                  ^
[Tue Aug 22 12:20:32.307563 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56144] SyntaxError: invalid syntax
[Tue Aug 22 12:20:32.648584 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146] mod_wsgi (pid=1808): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:32.648687 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146] mod_wsgi (pid=1808): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:32.648767 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146] Traceback (most recent call last):
[Tue Aug 22 12:20:32.648847 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:20:32.648945 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:20:32.649113 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:20:32.649139 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146]     raise AssertionError(msg) from exc
[Tue Aug 22 12:20:32.649165 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146]                                  ^
[Tue Aug 22 12:20:32.649187 2023] [wsgi:error] [pid 1808:tid 1966507008] [remote 127.0.0.1:56146] SyntaxError: invalid syntax
[Tue Aug 22 12:20:33.009366 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148] mod_wsgi (pid=1808): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:33.009500 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148] mod_wsgi (pid=1808): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:20:33.009610 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148] Traceback (most recent call last):
[Tue Aug 22 12:20:33.009702 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:20:33.009835 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:20:33.010044 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:20:33.010080 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148]     raise AssertionError(msg) from exc
[Tue Aug 22 12:20:33.010110 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148]                                  ^
[Tue Aug 22 12:20:33.010137 2023] [wsgi:error] [pid 1808:tid 1932936192] [remote 127.0.0.1:56148] SyntaxError: invalid syntax
[Tue Aug 22 12:24:08.481736 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346] mod_wsgi (pid=539): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:24:08.483868 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346] mod_wsgi (pid=539): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:24:08.484007 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346] Traceback (most recent call last):
[Tue Aug 22 12:24:08.484135 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:24:08.484406 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:24:08.484647 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:24:08.484684 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346]     raise AssertionError(msg) from exc
[Tue Aug 22 12:24:08.484706 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346]                                  ^
[Tue Aug 22 12:24:08.484726 2023] [wsgi:error] [pid 539:tid 1966748672] [remote 127.0.0.1:34346] SyntaxError: invalid syntax
[Tue Aug 22 12:30:09.678268 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356] mod_wsgi (pid=1490): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:30:09.678841 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356] mod_wsgi (pid=1490): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:30:09.678984 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356] Traceback (most recent call last):
[Tue Aug 22 12:30:09.679074 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:30:09.679373 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:30:09.682818 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:30:09.682967 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356]     raise AssertionError(msg) from exc
[Tue Aug 22 12:30:09.682997 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356]                                  ^
[Tue Aug 22 12:30:09.683019 2023] [wsgi:error] [pid 1490:tid 1966699520] [remote 127.0.0.1:34356] SyntaxError: invalid syntax
[Tue Aug 22 12:52:18.028874 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800] mod_wsgi (pid=551): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:52:18.030218 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800] mod_wsgi (pid=551): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 12:52:18.030387 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800] Traceback (most recent call last):
[Tue Aug 22 12:52:18.030482 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 5, in <module>
[Tue Aug 22 12:52:18.030753 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800]     exec(compile(open(activate_this, "rb").read(), activate_this, 'exec'))
[Tue Aug 22 12:52:18.030953 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 12:52:18.030986 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800]     raise AssertionError(msg) from exc
[Tue Aug 22 12:52:18.031008 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800]                                  ^
[Tue Aug 22 12:52:18.031028 2023] [wsgi:error] [pid 551:tid 1966887936] [remote 127.0.0.1:57800] SyntaxError: invalid syntax
[Tue Aug 22 13:01:41.204823 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812] mod_wsgi (pid=551): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:01:41.205103 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812] mod_wsgi (pid=551): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:01:41.205376 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812] Traceback (most recent call last):
[Tue Aug 22 13:01:41.205546 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 13:01:41.205952 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 13:01:41.206184 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812]   File "/var/www/CatFeeder/catenv/bin/activate_this.py", line 18
[Tue Aug 22 13:01:41.206219 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812]     raise AssertionError(msg) from exc
[Tue Aug 22 13:01:41.206244 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812]                                  ^
[Tue Aug 22 13:01:41.206268 2023] [wsgi:error] [pid 551:tid 1941709824] [remote 127.0.0.1:57812] SyntaxError: invalid syntax
[Tue Aug 22 13:57:44.363246 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532] mod_wsgi (pid=1344): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:57:44.364476 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532] mod_wsgi (pid=1344): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:57:44.365267 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532] Traceback (most recent call last):
[Tue Aug 22 13:57:44.365375 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 13:57:44.365397 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 13:57:44.365474 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56532] NameError: name 'execfile' is not defined
[Tue Aug 22 13:57:44.729820 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531] mod_wsgi (pid=1344): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:57:44.729986 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531] mod_wsgi (pid=1344): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 13:57:44.730273 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531] Traceback (most recent call last):
[Tue Aug 22 13:57:44.730364 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 13:57:44.730385 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 13:57:44.730448 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56531] NameError: name 'execfile' is not defined
[Tue Aug 22 14:04:54.896764 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652] mod_wsgi (pid=1344): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:04:54.897091 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652] mod_wsgi (pid=1344): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:04:54.897586 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652] Traceback (most recent call last):
[Tue Aug 22 14:04:54.897764 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:04:54.897812 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:04:54.897942 2023] [wsgi:error] [pid 1344:tid 1965298688] [remote 192.168.86.91:56652] NameError: name 'execfile' is not defined
[Tue Aug 22 14:04:55.347382 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651] mod_wsgi (pid=1344): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:04:55.347651 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651] mod_wsgi (pid=1344): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:04:55.348142 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651] Traceback (most recent call last):
[Tue Aug 22 14:04:55.348314 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:04:55.348362 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:04:55.348489 2023] [wsgi:error] [pid 1344:tid 1931727872] [remote 192.168.86.91:56651] NameError: name 'execfile' is not defined
[Tue Aug 22 14:07:57.948696 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747] mod_wsgi (pid=1315): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:07:57.950695 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747] mod_wsgi (pid=1315): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:07:57.951493 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747] Traceback (most recent call last):
[Tue Aug 22 14:07:57.951603 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:07:57.951626 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:07:57.951710 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56747] NameError: name 'execfile' is not defined
[Tue Aug 22 14:07:58.350239 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746] mod_wsgi (pid=1315): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:07:58.350419 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746] mod_wsgi (pid=1315): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:07:58.350707 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746] Traceback (most recent call last):
[Tue Aug 22 14:07:58.350794 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:07:58.350814 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:07:58.350876 2023] [wsgi:error] [pid 1315:tid 1932108800] [remote 192.168.86.91:56746] NameError: name 'execfile' is not defined
[Tue Aug 22 14:08:01.273125 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745] mod_wsgi (pid=1315): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:08:01.273422 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745] mod_wsgi (pid=1315): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:08:01.273945 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745] Traceback (most recent call last):
[Tue Aug 22 14:08:01.274126 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:08:01.274176 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:08:01.274313 2023] [wsgi:error] [pid 1315:tid 1965679616] [remote 192.168.86.91:56745] NameError: name 'execfile' is not defined
[Tue Aug 22 14:17:35.089846 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034] mod_wsgi (pid=1794): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:17:35.090096 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034] mod_wsgi (pid=1794): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:17:35.090774 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034] Traceback (most recent call last):
[Tue Aug 22 14:17:35.090870 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:17:35.090891 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:17:35.090957 2023] [wsgi:error] [pid 1794:tid 1964872704] [remote 192.168.86.91:57034] NameError: name 'execfile' is not defined
[Tue Aug 22 14:17:35.399866 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033] mod_wsgi (pid=1794): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:17:35.400021 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033] mod_wsgi (pid=1794): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 14:17:35.400292 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033] Traceback (most recent call last):
[Tue Aug 22 14:17:35.400376 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 4, in <module>
[Tue Aug 22 14:17:35.400397 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033]     execfile(activate_this, dict(__file__=activate_this))
[Tue Aug 22 14:17:35.400459 2023] [wsgi:error] [pid 1794:tid 1931301888] [remote 192.168.86.91:57033] NameError: name 'execfile' is not defined
[Tue Aug 22 16:47:06.950438 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:06.952539 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:06.954271 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194] Traceback (most recent call last):
[Tue Aug 22 16:47:06.954427 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:06.954452 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]     from app import app as application
[Tue Aug 22 16:47:06.954486 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:06.954504 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]     import commonTasks
[Tue Aug 22 16:47:06.954563 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:06.954603 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]     return 'ok'
[Tue Aug 22 16:47:06.954685 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194]               ^
[Tue Aug 22 16:47:06.954724 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62194] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:07.352469 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:07.352675 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:07.353063 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195] Traceback (most recent call last):
[Tue Aug 22 16:47:07.353237 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:07.353259 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]     from app import app as application
[Tue Aug 22 16:47:07.353291 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:07.353310 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]     import commonTasks
[Tue Aug 22 16:47:07.353367 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:07.353409 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]     return 'ok'
[Tue Aug 22 16:47:07.353493 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195]               ^
[Tue Aug 22 16:47:07.353533 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62195] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:08.592049 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:08.592388 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:08.593122 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199] Traceback (most recent call last):
[Tue Aug 22 16:47:08.593349 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:08.593397 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]     from app import app as application
[Tue Aug 22 16:47:08.593471 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:08.593514 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]     import commonTasks
[Tue Aug 22 16:47:08.593635 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:08.593727 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]     return 'ok'
[Tue Aug 22 16:47:08.593900 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199]               ^
[Tue Aug 22 16:47:08.593991 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62199] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:08.761060 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:08.761387 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:08.762121 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198] Traceback (most recent call last):
[Tue Aug 22 16:47:08.762342 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:08.762390 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]     from app import app as application
[Tue Aug 22 16:47:08.762464 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:08.762507 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]     import commonTasks
[Tue Aug 22 16:47:08.762626 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:08.762792 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]     return 'ok'
[Tue Aug 22 16:47:08.762965 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198]               ^
[Tue Aug 22 16:47:08.763054 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62198] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:09.717741 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:09.718086 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:09.718830 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202] Traceback (most recent call last):
[Tue Aug 22 16:47:09.719100 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:09.719158 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]     from app import app as application
[Tue Aug 22 16:47:09.719223 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:09.719260 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]     import commonTasks
[Tue Aug 22 16:47:09.719374 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:09.719455 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]     return 'ok'
[Tue Aug 22 16:47:09.719612 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202]               ^
[Tue Aug 22 16:47:09.719690 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62202] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:09.921577 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:09.921900 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:09.922573 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201] Traceback (most recent call last):
[Tue Aug 22 16:47:09.922775 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:09.922818 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]     from app import app as application
[Tue Aug 22 16:47:09.922878 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:09.922912 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]     import commonTasks
[Tue Aug 22 16:47:09.923012 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:09.923085 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]     return 'ok'
[Tue Aug 22 16:47:09.923227 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201]               ^
[Tue Aug 22 16:47:09.923301 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62201] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:10.329838 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.330126 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.330774 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204] Traceback (most recent call last):
[Tue Aug 22 16:47:10.330948 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:10.330983 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]     from app import app as application
[Tue Aug 22 16:47:10.331038 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:10.331071 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]     import commonTasks
[Tue Aug 22 16:47:10.331162 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:10.331231 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]     return 'ok'
[Tue Aug 22 16:47:10.331366 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204]               ^
[Tue Aug 22 16:47:10.331433 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62204] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:10.496062 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.496343 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.496992 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203] Traceback (most recent call last):
[Tue Aug 22 16:47:10.497190 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:10.497231 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]     from app import app as application
[Tue Aug 22 16:47:10.497295 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:10.497333 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]     import commonTasks
[Tue Aug 22 16:47:10.497438 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:10.497516 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]     return 'ok'
[Tue Aug 22 16:47:10.497667 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203]               ^
[Tue Aug 22 16:47:10.497744 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62203] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:10.888052 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.888519 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:10.889294 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206] Traceback (most recent call last):
[Tue Aug 22 16:47:10.889524 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:10.889574 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]     from app import app as application
[Tue Aug 22 16:47:10.889649 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:10.889753 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]     import commonTasks
[Tue Aug 22 16:47:10.889892 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:10.889985 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]     return 'ok'
[Tue Aug 22 16:47:10.890155 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206]               ^
[Tue Aug 22 16:47:10.890245 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62206] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:11.065222 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.065566 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.066319 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205] Traceback (most recent call last):
[Tue Aug 22 16:47:11.066544 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:11.066592 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]     from app import app as application
[Tue Aug 22 16:47:11.066666 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:11.066709 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]     import commonTasks
[Tue Aug 22 16:47:11.066830 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:11.066925 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]     return 'ok'
[Tue Aug 22 16:47:11.067098 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205]               ^
[Tue Aug 22 16:47:11.067189 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62205] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:11.520806 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.521097 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.521753 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207] Traceback (most recent call last):
[Tue Aug 22 16:47:11.521945 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:11.521986 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]     from app import app as application
[Tue Aug 22 16:47:11.522050 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:11.522087 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]     import commonTasks
[Tue Aug 22 16:47:11.522192 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:11.522272 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]     return 'ok'
[Tue Aug 22 16:47:11.522422 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207]               ^
[Tue Aug 22 16:47:11.522499 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62207] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:11.696639 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.697047 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:11.697872 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208] Traceback (most recent call last):
[Tue Aug 22 16:47:11.698165 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:11.698220 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]     from app import app as application
[Tue Aug 22 16:47:11.698298 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:11.698342 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]     import commonTasks
[Tue Aug 22 16:47:11.698481 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:11.698578 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]     return 'ok'
[Tue Aug 22 16:47:11.698772 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208]               ^
[Tue Aug 22 16:47:11.698865 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62208] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:12.328257 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.328599 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.329336 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211] Traceback (most recent call last):
[Tue Aug 22 16:47:12.329563 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:12.329612 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]     from app import app as application
[Tue Aug 22 16:47:12.329686 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:12.329729 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]     import commonTasks
[Tue Aug 22 16:47:12.329850 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:12.329944 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]     return 'ok'
[Tue Aug 22 16:47:12.330113 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211]               ^
[Tue Aug 22 16:47:12.330204 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62211] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:12.506866 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.507166 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.507897 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210] Traceback (most recent call last):
[Tue Aug 22 16:47:12.508122 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:12.508171 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]     from app import app as application
[Tue Aug 22 16:47:12.508318 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:12.508363 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]     import commonTasks
[Tue Aug 22 16:47:12.508486 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:12.508580 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]     return 'ok'
[Tue Aug 22 16:47:12.508753 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210]               ^
[Tue Aug 22 16:47:12.508845 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62210] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:12.880562 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.881037 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:12.881708 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213] Traceback (most recent call last):
[Tue Aug 22 16:47:12.881905 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:12.881946 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]     from app import app as application
[Tue Aug 22 16:47:12.882009 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:12.882046 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]     import commonTasks
[Tue Aug 22 16:47:12.882151 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:12.882231 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]     return 'ok'
[Tue Aug 22 16:47:12.882383 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213]               ^
[Tue Aug 22 16:47:12.882460 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62213] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:13.050398 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:13.050668 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:13.051238 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212] Traceback (most recent call last):
[Tue Aug 22 16:47:13.051411 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:13.051447 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]     from app import app as application
[Tue Aug 22 16:47:13.051503 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:13.051536 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]     import commonTasks
[Tue Aug 22 16:47:13.051629 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:13.051701 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]     return 'ok'
[Tue Aug 22 16:47:13.051838 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212]               ^
[Tue Aug 22 16:47:13.051968 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62212] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:14.916190 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:14.916494 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:14.917147 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214] Traceback (most recent call last):
[Tue Aug 22 16:47:14.917345 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:14.917387 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]     from app import app as application
[Tue Aug 22 16:47:14.917450 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:14.917486 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]     import commonTasks
[Tue Aug 22 16:47:14.917591 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:14.917671 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]     return 'ok'
[Tue Aug 22 16:47:14.917820 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214]               ^
[Tue Aug 22 16:47:14.917897 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62214] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:15.095682 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.095973 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.096571 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215] Traceback (most recent call last):
[Tue Aug 22 16:47:15.096744 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:15.096781 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]     from app import app as application
[Tue Aug 22 16:47:15.096835 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:15.096868 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]     import commonTasks
[Tue Aug 22 16:47:15.096963 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:15.097034 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]     return 'ok'
[Tue Aug 22 16:47:15.097169 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215]               ^
[Tue Aug 22 16:47:15.097237 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62215] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:15.478085 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.478396 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.479172 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217] Traceback (most recent call last):
[Tue Aug 22 16:47:15.479501 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:15.479549 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]     from app import app as application
[Tue Aug 22 16:47:15.479623 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:15.479666 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]     import commonTasks
[Tue Aug 22 16:47:15.479793 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:15.479886 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]     return 'ok'
[Tue Aug 22 16:47:15.480178 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217]               ^
[Tue Aug 22 16:47:15.480275 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62217] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:15.863153 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.863455 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:15.864173 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218] Traceback (most recent call last):
[Tue Aug 22 16:47:15.864397 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:15.864446 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]     from app import app as application
[Tue Aug 22 16:47:15.864521 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:15.864564 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]     import commonTasks
[Tue Aug 22 16:47:15.864686 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:15.864780 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]     return 'ok'
[Tue Aug 22 16:47:15.864954 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218]               ^
[Tue Aug 22 16:47:15.865144 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62218] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:16.122583 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.122932 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.126098 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219] Traceback (most recent call last):
[Tue Aug 22 16:47:16.126431 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:16.126482 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]     from app import app as application
[Tue Aug 22 16:47:16.126541 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:16.126573 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]     import commonTasks
[Tue Aug 22 16:47:16.126840 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:16.126981 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]     return 'ok'
[Tue Aug 22 16:47:16.127130 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219]               ^
[Tue Aug 22 16:47:16.127199 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62219] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:16.401007 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.401319 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.402044 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220] Traceback (most recent call last):
[Tue Aug 22 16:47:16.402272 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:16.402320 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]     from app import app as application
[Tue Aug 22 16:47:16.402394 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:16.402438 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]     import commonTasks
[Tue Aug 22 16:47:16.402561 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:16.402655 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]     return 'ok'
[Tue Aug 22 16:47:16.402825 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220]               ^
[Tue Aug 22 16:47:16.402915 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62220] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:16.661089 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.661363 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:16.661992 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216] Traceback (most recent call last):
[Tue Aug 22 16:47:16.662188 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:16.662229 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]     from app import app as application
[Tue Aug 22 16:47:16.662293 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:16.662330 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]     import commonTasks
[Tue Aug 22 16:47:16.662436 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:16.662515 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]     return 'ok'
[Tue Aug 22 16:47:16.662665 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216]               ^
[Tue Aug 22 16:47:16.662743 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62216] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:21.294748 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:21.295207 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:21.297925 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222] Traceback (most recent call last):
[Tue Aug 22 16:47:21.298190 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:21.298241 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]     from app import app as application
[Tue Aug 22 16:47:21.298315 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:21.298358 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]     import commonTasks
[Tue Aug 22 16:47:21.298483 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:21.298577 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]     return 'ok'
[Tue Aug 22 16:47:21.298756 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222]               ^
[Tue Aug 22 16:47:21.298845 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62222] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:21.495999 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:21.496361 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:21.497118 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221] Traceback (most recent call last):
[Tue Aug 22 16:47:21.497341 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:21.497389 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]     from app import app as application
[Tue Aug 22 16:47:21.497463 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:21.497507 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]     import commonTasks
[Tue Aug 22 16:47:21.497628 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:21.497720 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]     return 'ok'
[Tue Aug 22 16:47:21.497895 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221]               ^
[Tue Aug 22 16:47:21.497986 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62221] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:22.070750 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:22.071035 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:22.071666 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224] Traceback (most recent call last):
[Tue Aug 22 16:47:22.071861 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:22.071902 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]     from app import app as application
[Tue Aug 22 16:47:22.071965 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:22.072069 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]     import commonTasks
[Tue Aug 22 16:47:22.072175 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:22.072254 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]     return 'ok'
[Tue Aug 22 16:47:22.072400 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224]               ^
[Tue Aug 22 16:47:22.072477 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62224] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:22.261970 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:22.262242 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:22.262875 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223] Traceback (most recent call last):
[Tue Aug 22 16:47:22.263068 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:22.263109 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]     from app import app as application
[Tue Aug 22 16:47:22.263171 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:22.263208 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]     import commonTasks
[Tue Aug 22 16:47:22.263313 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:22.263393 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]     return 'ok'
[Tue Aug 22 16:47:22.263541 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223]               ^
[Tue Aug 22 16:47:22.263619 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62223] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:23.598795 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:23.599125 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:23.599842 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226] Traceback (most recent call last):
[Tue Aug 22 16:47:23.600067 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:23.600116 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]     from app import app as application
[Tue Aug 22 16:47:23.600190 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:23.600233 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]     import commonTasks
[Tue Aug 22 16:47:23.600356 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:23.600447 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]     return 'ok'
[Tue Aug 22 16:47:23.600618 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226]               ^
[Tue Aug 22 16:47:23.600708 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62226] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:23.813281 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:23.813620 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:23.814209 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225] Traceback (most recent call last):
[Tue Aug 22 16:47:23.814382 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:23.814418 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]     from app import app as application
[Tue Aug 22 16:47:23.814474 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:23.814506 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]     import commonTasks
[Tue Aug 22 16:47:23.814598 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:23.814667 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]     return 'ok'
[Tue Aug 22 16:47:23.814802 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225]               ^
[Tue Aug 22 16:47:23.814871 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62225] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:24.379615 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:24.379933 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:24.380594 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228] Traceback (most recent call last):
[Tue Aug 22 16:47:24.380789 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:24.380831 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]     from app import app as application
[Tue Aug 22 16:47:24.380895 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:24.380932 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]     import commonTasks
[Tue Aug 22 16:47:24.381039 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:24.381119 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]     return 'ok'
[Tue Aug 22 16:47:24.381273 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228]               ^
[Tue Aug 22 16:47:24.381351 2023] [wsgi:error] [pid 4280:tid 1931199488] [remote 192.168.86.91:62228] IndentationError: unindent does not match any outer indentation level
[Tue Aug 22 16:47:24.555272 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227] mod_wsgi (pid=4280): Failed to exec Python script file '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:24.555582 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227] mod_wsgi (pid=4280): Exception occurred processing WSGI script '/var/www/CatFeeder/CatFeeder.wsgi'.
[Tue Aug 22 16:47:24.556210 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227] Traceback (most recent call last):
[Tue Aug 22 16:47:24.556401 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]   File "/var/www/CatFeeder/CatFeeder.wsgi", line 9, in <module>
[Tue Aug 22 16:47:24.556443 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]     from app import app as application
[Tue Aug 22 16:47:24.556571 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]   File "/var/www/CatFeeder/app.py", line 9, in <module>
[Tue Aug 22 16:47:24.556608 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]     import commonTasks
[Tue Aug 22 16:47:24.556713 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]   File "/var/www/CatFeeder/commonTasks.py", line 158
[Tue Aug 22 16:47:24.556793 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]     return 'ok'
[Tue Aug 22 16:47:24.556944 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227]               ^
[Tue Aug 22 16:47:24.557022 2023] [wsgi:error] [pid 4280:tid 1964770304] [remote 192.168.86.91:62227] IndentationError: unindent does not match any outer indentation level
